### ISSUE TITLE
Does it support already exists cloudfront distribution?

### ISSUE THREAD

**Issue by timandy** [aws-samples/image-optimization#10]

**Comment by achrafsouk** [comment]
This should be possible by changing the CDK code to reuse your existing distribution https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.DistributionAttributes.html

You need to be careful though not to make un desired changes on the existing one, assuming its carrying production traffic

**Comment by HieronyM** [comment]
Sorry to ask on closed issue,

So I want to deploy the solution on already exist Cloudfront distribution. I have a static website host in **bucket X**, but the web get asset from **bucket Y**. 

To deploy it, what command should I use? `cdk deploy -c S3_IMAGE_BUCKET_NAME='bucket-X'` or `cdk deploy -c S3_IMAGE_BUCKET_NAME='bucket-Y'`?


Thank you
