### ISSUE TITLE
not serving optimized version

### ISSUE THREAD

**Issue by berkmh** [aws-samples/image-optimization#11]
got this installed today. 

1/ I am able to access the normal image directly from the new cloudfront dist url
2/ I am able to access the optimized version directly by appending url with ?format=auto&width=300
3/ but when requesting from site only the normal unoptimized image is served. 

this is being done on a existing Wordpress site using an existing bucket, not sure if that matters or not. what could be going wrong? do I need to update anything on the existing bucket for this to work?

**Comment by achrafsouk** [comment]
Can you share your website url so I can have a look?

**Comment by berkmh** [comment]
yes, its https://www.cannabox.com

also, I tried running this though a CNAME and it seems to not work and tries to redirect back to my origin getting a too many redirects error....if I run direct though the cloudfront url it works, again without optimization. can you have a look please. thanks

**Comment by berkmh** [comment]
I also noticed when I try to access one of the images stored in the optimized bucket directly I get a 403 access denied. not sure if that is expected or not...

**Comment by achrafsouk** [comment]
Just checked your website.
1/ your frontend is not requesting any transformations using query strings, this is why the solution is defaulting to the original image. 
2/ Its normal that you cant access images directly from the S3 bucket, its an intentional security control.

**Comment by berkmh** [comment]
> 1/ your frontend is not requesting any transformations using query strings, this is why the solution is defaulting to the original image.

thanks! 

do you happen to know how to make that happen within Wordpress?

**Comment by achrafsouk** [comment]
i can explore that in the next weeks, but I guess a small change to the CloudFront Function to read transformations as requested by WP should do the trick.

**Comment by berkmh** [comment]
thank you sir :)

**Comment by achrafsouk** [comment]
based on this [article](https://enginescout.com.au/wordpress-image-sizes/#:~:text=Changing%20WordPress%20Default%20Image%20sizes&text=Go%20to%20your%20WordPress%20Admin,Click%20Save%20Changes%20to%20confirm), it seems that wordpress creates multiple sizes of uploaded images, and its frontend uses the most appropriate one according to screen (responsive design). So the question is what do you need the image optimisation solution for?

**Comment by achrafsouk** [comment]
If its just to serve different formats of the images (jpeg, webp, avif), than you can change the code of the CloudFront Function to the below: 

function handler(event) {
    var request = event.request;
		var format = 'jpeg';
		if (request.headers['accept']) {
       if (request.headers['accept'].value.includes("avif")) { format = 'avif';} 
		   else if (request.headers['accept'].value.includes("webp")) { format = 'webp'; } 
    }
		request.uri =  request.uri + '/format=' + format;
    request['querystring'] = {};
    return request;
}

**Comment by achrafsouk** [comment]
Please consider this as sample code, and test it before running in prod. I quickly made it on my mobile phone to avoid keeping you waiting till I come back from PTO.

**Comment by berkmh** [comment]
that worked great! thank you again sir!

**Comment by achrafsouk** [comment]
awesome
