### ISSUE TITLE
Adapting to Support Videos

### ISSUE THREAD

**Issue by larrettgee** [aws-samples/image-optimization#23]
First of all, thanks so much for the construction of this repository. It made getting my image CDN and optimization off the ground pretty easy!

The web app I'm building on is aiming to support both image and video types. Is there a way to adapt this repo to handle mov, mp4, and so forth?

Thanks in advance!

**Comment by achrafsouk** [comment]
Hello! what is the use case?

**Comment by larrettgee** [comment]
I'm looking to optimize user submitted videos in the same way this repo currently optimizes photos!

**Comment by achrafsouk** [comment]
I think that the video workflow is different. The image one is done in the fly synchronously when an image is requested. For Video i think it makes more sense to do it asynch when the video is uploaded.

**Comment by larrettgee** [comment]
Thanks for the advice and makes sense! Do you have any references on where I could get some guidance on that approach?

**Comment by achrafsouk** [comment]
check this https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/
