### ISSUE TITLE
A single cloudfront

### ISSUE THREAD

**Issue by CifGom** [aws-samples/image-optimization#25]
Could everything work with a single cloudfront distribution? or with two distributions and a single subdomain?

**Comment by achrafsouk** [comment]
it's easily possible using the same distribution. You need to create a dedicated behavior for image processing, and configure the solution on it. 

The other proposal is not an option. You can configure two CloudFront distributions with the same domain.

**Comment by CifGom** [comment]
Thanks for the info. I'll try it on Monday, if there's something wrong I'll let you know in case you can help me.
Thank you so much

**Comment by achrafsouk** [comment]
check this https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/
