### ISSUE TITLE
Set own transformed bucket name

### ISSUE THREAD

**Issue by pawlakzn** [aws-samples/image-optimization#29]
There is a possibility to set different own parameters, e.g.: `S3_IMAGE_BUCKET_NAME`.

Would you it be possible to set own name of transformed bucket? For example as `S3_TRANSFORMED_IMAGE_BUCKET_NAME`?

**Comment by achrafsouk** [comment]
Yes, it's simple, you need to change the lib/image-optimization-stack.ts code. 

instead of _transformedImageBucket = new s3.Bucket(...._ use _transformedImageBucket = s3.Bucket.fromBucketName(_

**Comment by pawlakzn** [comment]
Thank you very much!
