### ISSUE TITLE
Could not load the \"sharp\" module using the linux-x64 runtime\nPossible

### ISSUE THREAD

**Issue by eyyazubi** [aws-samples/image-optimization#40]
i got:
-------
 "errorType": "Error",
  "errorMessage": "Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install"...
-------

and fixed with root package.json
line 8:
prev:
    "prebuild": "npm install  sharp --prefix functions/image-processing/ --os=linux --cpu=x64"

TO:
    "prebuild": "npm install --force sharp --prefix functions/image-processing/ --os=linux --cpu=x64"

**Comment by achrafsouk** [comment]
It did not work for me (i am using Mac)

**Comment by eyyazubi** [comment]
I also use mac. I haven't tested it at all on the mac. It comes in Lambda functions on aws.

**Comment by eyyazubi** [comment]
i had a "internal error" message, when i try visit to the images via cloudfront url and saw the error in the lambda functions under code source

**Comment by maiconcarraro** [comment]
I had this error because I deployed without running the build before, after running the build it was working fine. I'm using node v22 and npm 10.6.0.

**Comment by dimasxp** [comment]
have the same problem, changed node version from 18 to 20,rebuild, now works fine

**Comment by ishanaudichya** [comment]
> It did not work for me (i am using Mac)

I think u re using an arm machine so the binary for sharp are not created 
![image](https://github.com/aws-samples/image-optimization/assets/93155612/8842ecfa-d0ec-4387-8eec-b23015c144e4)

This will work fine on x86 machines. To get around this use post build instead of prebuild in package.json
![image](https://github.com/aws-samples/image-optimization/assets/93155612/570084bd-412e-46b8-b2ec-00439b0eeb58)

Like this and it will work fine. 
Lmk if it works out.

**Comment by bracki** [comment]
Switched to Node 20 from 18. Now it works. 🎉
