### ISSUE TITLE
No exported member 'ImageOptimizationStack'

### ISSUE THREAD

**Issue by lennartkerkvliet** [aws-samples/image-optimization#52]
Since the [latest commit](https://github.com/aws-samples/image-optimization/commit/ae4624bb2dcef16e71a6ef37395f3cce6a18dded) on `main`, the sample code can no longer be deployed. It seems like 

```
import { ImageOptimizationStack } from '../lib/image-optimization-stack';
``` 

can no longer be fulfilled after the renaming to `StoreInfraStack`. I suppose this is a mistake?

**Comment by achrafsouk** [comment]
Sorry this is a mistake, I will correct today

**Comment by achrafsouk** [comment]
Just reverted this erronous commit, thanks for raising it
