### ISSUE TITLE
Cannot find package 'sharp' imported from /var/task/index.mjs

### ISSUE THREAD

**Issue by IhebMarnaoui** [aws-samples/image-optimization#55]
I get the error when I try to get the images from the distribution at the img transformation lambda function level:
2024-08-29T20:10:01.192Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find package 'sharp' imported from /var/task/index.mjs",
    "code": "ERR_MODULE_NOT_FOUND",
    "stack": [
        "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'sharp' imported from /var/task/index.mjs",
        "    at packageResolve (node:internal/modules/esm/resolve:858:9)",
        "    at moduleResolve (node:internal/modules/esm/resolve:931:18)",
        "    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1173:14)",
        "    at defaultResolve (node:internal/modules/esm/resolve:1216:79)",
        "    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)",
        "    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)",
        "    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)",
        "    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)",
        "    at link (node:internal/modules/esm/module_job:86:36)"
    ]
}

It seems like there's a bundling problem with  image-processing lambda and the related packages, can anyone take a look please ? thank you!

**Comment by piotrekwitkowski** [comment]
Hi @IhebMarnaoui, most likely the deps  were not installed correctly. Can you confirm the deployment size of your lambda function? Did you run `npm run build` before `cdk deploy` like described in the readme? If so, you should have a new node_modules directory under functions/image-processing/ with sharp. Also, what OS are you running?

You can trigger manual installation of deps by running `npm run prebuild` too

**Comment by IhebMarnaoui** [comment]
Thanks for the response, yes, after investigating, it turned out that my OS is the issue because it is unable to to install these linux-64x dependencies while Im using arm64 (I have an M2 mac), would you have an idea on what to do in my case ? 
Thank you!

**Comment by piotrekwitkowski** [comment]
I am able to install the deps and deploy the solution from an M1 Mac. What is the output of the command `npm run prebuild` on your machine and what is the deployment size of the Lambda function in your AWS account?

<img width="1027" alt="Screenshot 2024-09-02 at 17 02 08" src="https://github.com/user-attachments/assets/21770cc0-eaf8-4638-bada-e36290fd8842">

**Comment by IhebMarnaoui** [comment]
This would be the output I get when I try to build my app:
```
Bundling asset hop-api-stack-backend/ob-article-media-image-optimization/Code/Stage...
npm error code EBADPLATFORM
npm error notsup Unsupported platform for @img/sharp-libvips-linux-x64@1.0.4: wanted {"os":"linux","cpu":"x64","libc":"glibc"} (current: {"os":"linux","cpu":"arm64","libc":"glibc"})
npm error notsup Valid os:    linux
npm error notsup Actual os:   linux
npm error notsup Valid cpu:   x64
npm error notsup Actual cpu:  arm64
npm error notsup Valid libc:  glibc
npm error notsup Actual libc: glibc
```

Please note that this is not the output of `npm run build` but this happens when I try to deploy (using cdk deploy), my setup is just a little more complicated than Im describing because I am building the image optimisation on an independent library and then when I publish this library locally, this happens. 
I tried running all of this on the cloud and it worked like charm so nothing wrong with the setup and my issue is invalid I have to admit, but I still wanna bypass this local error because I am now unable to work locally due to it and I would like to do some of testing locally most of the time so it would be nice if I can somehow bypass this error.

**Comment by LionisIAm** [comment]
@IhebMarnaoui 
try to build after `npm install --os=linux --cpu=x64 sharp`

**Comment by etiennemunnich** [comment]
Tried moving from node18 to node 20 - no joy.

Tried npm install --os=linux --cpu=x64 sharp - no dice yet (didn't work)

Also using mac with apple silicon.

Lambda execution yields this error:

```
Could not load the \"sharp\" module using the linux-x64 runtime\nERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
    "stack": [
        "Error: Could not load the \"sharp\" module using the linux-x64 runtime",
        "ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory",
        "Possible solutions:",
        "- Ensure optional dependencies can be installed:",
        "    npm install --include=optional sharp",
        "- Ensure your package manager supports multi-platform installation:",
        "    See https://sharp.pixelplumbing.com/install#cross-platform",
        "- Add platform-specific dependencies:",
        "    npm install --os=linux --cpu=x64 sharp",
        "- Consult the installation documentation:",
        "    See https://sharp.pixelplumbing.com/install",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:113:9)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1288:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1104:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1311:19)",
        "    at require (node:internal/modules/helpers:179:18)",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:1)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)"
    ]
}
```

**Comment by achrafsouk** [comment]
got the same this morning, looking to it

**Comment by cubatic45** [comment]
same error
```
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
```

**Comment by cubatic45** [comment]
I got it, restore to this commit: cc1eb326d2b1203cf64cda3ccf211686df6e378a

**Comment by IhebMarnaoui** [comment]
@cubatic45 I agree! That's actually the only thing that worked for me since I opened this issue

**Comment by piotrekwitkowski** [comment]
Hi @IhebMarnaoui, @cubatic45, thanks again for reporting this. Reverted the change - we're now using the Sharp installation method described here: https://sharp.pixelplumbing.com/install#npm-v10.

**Comment by piotrekwitkowski** [comment]
For context, to check if you have correct deps installed:
```shell
# check if sharp-libvips-linux-x64 and sharp-linux-x64 are present
ls functions/image-processing/node_modules/@img

# check if libvips-cpp.so.42 is present
ls functions/image-processing/node_modules/@img/sharp-libvips-linux-x64/lib
```

Please keep in mind that `--cpu` and `--os` flags are supported by npm v10+ only. Also, `--libc` is best supported on npm v10.4.0+, as it correctly drops musl deps, reducing overall size of the Lambda function.
