### ISSUE TITLE
[BUG?] Potential CHR issue with enabled compression in cache behavior

### ISSUE THREAD

**Issue by artemfdev** [aws-samples/image-optimization#59]
Current code creates CloudFront's cache behavior with "Compress objects automatically: Yes". In [the documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-notes) it is stated that in this case CloudFront adds `Accept-Encoding` to the cache key automatically:

> When CloudFront is configured to compress objects, it includes the Accept-Encoding header in the cache key and in origin requests automatically

So if this is the case, that means that single image url is cached multiple times, depending on the client's `Accept-Encoding` header, which in turn results in significantly lower Cache Hit Ratio. Not to mention the implementation doesn't need or use `Accept-Encoding` header at all. It looks to me that for this setup we just need to turn off the automatic compression (it's on by default). 

I'm not a pro in AWS, but [according to documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#aws-properties-cloudfront-distribution-defaultcachebehavior-properties) you can add this line to fix the issue:
```
var imageDeliveryCacheBehaviorConfig = {
            origin: imageOrigin,
            Compress: false,
            ...
```

Thank you for your attention, please correct me if I'm wrong with my assumptions.

**Comment by achrafsouk** [comment]
Hello! 

Thanks for the feedback. In the code, compression is not explicitly configured, leaving it to the default value which is false according to documentation.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.CfnDistribution.CacheBehaviorProperty.html#compress

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.CachePolicy.html#enableacceptencodingbrotli

So, I do not see why you end up with a CloudFront distribution with "Compress objects automatically: Yes". Can you share more details?

**Comment by artemfdev** [comment]
Thanks for reply, Achraf!

I just deployed the solution using `cdk deploy` to my test account as per [this article](https://aws.amazon.com/blogs/networking-and-content-delivery/image-optimization-using-amazon-cloudfront-and-aws-lambda/).

Regarding the default values, I can confirm this: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.CachePolicy.html#enableacceptencodingbrotli
Both gzip and brotli were disabled in the cache policy after the deployment.

But in this case: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.CfnDistribution.CacheBehaviorProperty.html#compress
I had compression on by default. Hmm, I need to check it's not a user error and I haven't accidentally changed the value myself. I will double-check and will get back to you with more info.

**Comment by artemfdev** [comment]
Getting back with the updates.

Re-run the deployment (`cdk destroy`, then `cdk deploy -c DEPLOY_SAMPLE_WEBSITE=true`), the cloudfront distribution for images is still created with "Compress objects automatically: Yes":

![screenshot_480](https://github.com/user-attachments/assets/962a34ec-f985-4524-96c4-efddae0a7211)

This is the correct distribution (image's), actually both distributions (image's & website's) have compression enabled. You can try it for yourself.

**Comment by achrafsouk** [comment]
You are right, the default seems to be compress, the documentation is wrong.

I will change it to disable compression in the code. However, I don't think it has any effect, because 1/ compression does not apply to image files, and 2/ the compression is not enabled in the cache policy

**Comment by achrafsouk** [comment]
https://github.com/aws-samples/image-optimization/commit/b0b731330b0b55ea5fd73c600fe0d0773b4d9b42

**Comment by achrafsouk** [comment]
https://github.com/aws-samples/image-optimization/commit/b0b731330b0b55ea5fd73c600fe0d0773b4d9b42

**Comment by artemfdev** [comment]
@achrafsouk Thank you!

> However, I don't think it has any effect, because 1/ compression does not apply to image files, and 2/ the compression is not enabled in the cache policy

Well, I don't know how to check the cache key, but since the documentation above says

> When CloudFront is configured to compress objects, it includes the Accept-Encoding header in the cache key and in origin requests automatically

It seems that the `Accept-Encoding` is added automatically to the cache key even **before** the request to the origin is done, so CloudFront can't know if it's an image or not (we don't know `Content-Type` before the request is completed). So it might not technically **perform** the compression, but I get the impression that the `Accept-Encoding` is added to the cache key anyway by the mere fact of **enabling** the compression.  Anyway, hard to tell it for sure without seeing the actual cache key, but IMO the potential performance cost too is high to leave it to chance.

Btw, does the current code working for you? When I do `cdk deploy` on the new code, it fails:
```
lib/image-optimization-stack.ts:216:9 - error TS2353: Object literal may only specify known properties, and 'compress' does not exist in type 'CachePolicyProps'.

216         compress: false
```

It looks to me the `compress` attribute is part of the Behavior, not CachePolicy. If I move `compress` up one level (to `ImageDeliveryCacheBehaviorConfig`) I can deploy the solution and then CloudFront image distribution displays "Compress objects automatically: No" as it should.

**Comment by achrafsouk** [comment]
Sorry, i made the change too quickly -> https://github.com/aws-samples/image-optimization/commit/8afd963812e203283872321ae14d7e2e40228b72

The documentation you are referring only applies to Legacy Caching settings. At that time, there CloudFront did not give you the configurability in the caching settings to control how it normalized Accept-Encoding header for the cache key. The referred doc was kind of a way to disable this normalization for content that does not need compression. With Cache policies, what we use in the solution, we have control over this Accept-Encoding header normalization in a proper way. 

We sent a message to the doc teams to make it clearer that this section related to Legacy Caching settings.

**Comment by LionisIAm** [comment]
After this PR was merged project is not building anymore
```
cdk bootstrap                                
/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/image-optimization-stack.ts:211:7 - error TS2353: Object literal may only specify known properties, and 'compress' does not exist in type 'ImageDeliveryCacheBehaviorConfig'.

211       compress: false,
          ~~~~~~~~

    at createTSError (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/home/paulefou/work/softpear/image-optimization/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  diagnosticCodes: [ 2353 ]
}

Subprocess exited with error 1
```

**Comment by artemfdev** [comment]
@LionisIAm You're right
@achrafsouk You need to add `compress` to `ImageDeliveryCacheBehaviorConfig` declaration (line 31):
```
type ImageDeliveryCacheBehaviorConfig = {
  origin: any;
  compress: any;
...
```

Sorry, no permissions to create a PR with the fix

**Comment by achrafsouk** [comment]
https://github.com/aws-samples/image-optimization/commit/1c264f0397824d5754647a00030b0c1bdb10108c
