### ISSUE TITLE
[Question] Cache Key Settings - Query strings All

### ISSUE THREAD

**Issue by chrisngcode** [aws-samples/image-optimization#61]
Hi there, understand that the Query string behavior is set to all (https://github.com/aws-samples/image-optimization/blob/main/lib/image-optimization-stack.ts#L217), is it really required to be set as All here? Cause as what i've tested and read from the readme ...

> ... the transformed image in response to /mycat.jpg?format=auto&width=200 would be stored with the key /mycat.jpg/format=webp,width=200

Did a test to invalidate 
- /mycat.jpg?format=auto&width=200 - doesn't work, i still get hits from CF
- /mycat.jpg/format=webp,width=200 - this invalidates and i get a Miss from CF

In this case, if we set to None, CF will still cache hits based on the key to the object. So if we set to None, will it affect the cache hit ratio for the implementation?

Please do let me know if i understand this incorrectly. Awesome stack by the way 😃

**Comment by achrafsouk** [comment]
Thank you, will have a look this week ^^

**Comment by achrafsouk** [comment]
You are right. It's not needed. Removing it would only have positive impact on CHR if you are using in the same time format=auto and specific formats (e.g. format=webp). In this case, the webp image will be cached in two different keys. 

https://github.com/aws-samples/image-optimization/commit/bb5eafee1da957ea6c1315761f16992285949229

thanks for your feedback / contribution

**Comment by chrisngcode** [comment]
Thanks @achrafsouk !
