### ISSUE TITLE
Is there possibility to bypass image transformation for non-image files and get it from original S3 bucket directly?

### ISSUE THREAD

**Issue by zakdma** [aws-samples/image-optimization#62]
Is not a bug but rather a question or improvement.
I store all files not only images in my original bucket. So I want to transform all image files like *.jpg, *.jpeg, *.bmp, *.png, *.gif.
All others (like zip, gz, doc, txt) just redirect to original S3 bucket without any transformation or additional handling
How can I achieve this?

Thank you!

**Comment by achrafsouk** [comment]
https://github.com/aws-samples/image-optimization/issues/31
