### ISSUE TITLE
Got Internal Server Error

### ISSUE THREAD

**Issue by stonesthatwhisper** [aws-samples/image-optimization#7]
After deploying this I got Internal Server Error when accessing: 

https://\<my-distribution\>.cloudfront.net/images/rio/1.jpeg?format=auto&width=300

What's the difference between this repo with
https://github.com/aws-solutions/serverless-image-handler

they do look similar but I would appreciate a comparison.

**Comment by achrafsouk** [comment]
Hello, in the HTTP response of the failed request, you will find the 'X-Amz-Cf-Id' Header. Can tou share the value of it? It will help me troubleshoot the issue.

Compared to the Serverless Image Handler, this architecture is optimized for end user delivery thanks to cache normalization, temporary storage with S3, and lower delivery cost without the API Gateway layer.

**Comment by achrafsouk** [comment]
FYI, I just deployed the stack again, and tested the same URL, i didn't have the issue you mention

**Comment by achrafsouk** [comment]
Maybe you are curling with a HEAD HTTP request? -I ? it's not allowed in the code, you can change it if you want.

**Comment by davidvanleeuwen** [comment]
Testing out what you've build and I actually have the same problem as @stonesthatwhisper. It seems to be an issue with the way you include sharp. 

![image](https://github.com/aws-samples/image-optimization/assets/238946/2002343f-663b-4722-be70-8b4ab11a8072)

I haven't done a lot lately AWS. I'll check if I can fix this myself.Not sure how dependencies are taken care of with CDK/lambda these days.

**Comment by davidvanleeuwen** [comment]
Ah lol, just forgetting to run `npm run build` 🤦
