### ISSUE TITLE
All bucket support

### ISSUE THREAD

**Issue by timandy** [aws-samples/image-optimization#9]
I tried to deployed this stack, it give the bucket thumb feature for one bucket.
But I have many bucket, should I deploy this stack repeatly?

I try deploy it for the second bucket, but shows below
![image](https://github.com/aws-samples/image-optimization/assets/3809541/d862b1b7-e0c2-4cc6-86eb-ced9a932b1f4)

**Comment by timandy** [comment]
I have resolved this problem. Thanks a lot.

**Comment by timandy** [comment]
@sbstnplcn Hi, you can fork my repo [MediaX](https://github.com/timandy/MediaX). 
You need to create a branch for each bucket that executes thumbnails, and modify the name of the stack and bucket in each branch Then deploy each branch.
I hope it can help you.

**Comment by mcosti** [comment]
@timandy I came into the same issue and I came up with this solution

```js
new ImageOptimizationStack(app, '1MediaBucketResize', {

}, "bucket-1");


new ImageOptimizationStack(app, '2MediaBucketResize', {

}, "bucket-2");


new ImageOptimizationStack(app, '3MediaBucketResize', {

}, "bucket-3");
```

But then I ran into an issue about the response headers policy already existing with this name.

So I had to change 
```js
        responseHeadersPolicyName: "ImageResponsePolicy",
```

into
```js
        responseHeadersPolicyName: `ImageResponsePolicy${this.node.addr}`,
```

On line 232 of image-optimization-stack.ts

Your fork seems to have a lot of QoL improvements, I just wish the comments in the codebase and readme would be in English
